---
# Deployer
- name: Create infosec app dir on deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/InfoSec_App_for_Splunk"
        state=directory
  when: "'deployer' in group_names"

- name: Copy InfoSec app to deployer
  unarchive: src="{{ splunk_repository.repository_root }}/apps/{{ splunk_apps.infosec_tgz }}"
          dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps"
          copy=yes
          owner=splunk
          group=splunk
  notify: shcluster bundle push
  when: "'deployer' in group_names"

# lets do this the stupid way?

- name: Create CIM app dir on deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_SA_CIM"
        state=directory
  when: "'deployer' in group_names"

- name: Copy CIM add-on to deployer
  unarchive: src="{{ splunk_repository.repository_root }}/apps/{{ splunk_apps.splunk_cim_tgz }}"
          dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps"
          copy=yes
          owner=splunk
          group=splunk
  notify: shcluster bundle push
  when: "'deployer' in group_names"

- name: Create punchcard viz dir on deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/punchcard_app"
        state=directory
  when: "'deployer' in group_names"

- name: Copy punchcard viz add-on to deployer
  unarchive: src="{{ splunk_repository.repository_root }}/apps/{{ splunk_apps.punchcard_tgz }}"
          dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps"
          copy=yes
          owner=splunk
          group=splunk
  notify: shcluster bundle push
  when: "'deployer' in group_names"

- name: Create force directed viz dir on deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/force_directed_viz"
        state=directory
  when: "'deployer' in group_names"

- name: Copy force directed viz add-on to deployer
  unarchive: src="{{ splunk_repository.repository_root }}/apps/{{ splunk_apps.force_directed_tgz }}"
          dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps"
          copy=yes
          owner=splunk
          group=splunk
  notify: shcluster bundle push
  when: "'deployer' in group_names"

- name: Create Lookup app dir on deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/lookup_editor"
        state=directory
  when: "'deployer' in group_names"

- name: Copy Lookup editor app to deployer
  unarchive: src="{{ splunk_repository.repository_root }}/apps/{{ splunk_apps.lookup_editor_tgz }}"
          dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps"
          copy=yes
          owner=splunk
          group=splunk
  notify: shcluster bundle push
  when: "'deployer' in group_names"
