---
- name: Push add-on to shcluster
  command: "./splunk apply shcluster-bundle --answer-yes -target https://{{ item }}:8089 -auth admin:{{ splunk_installation.admin_password }} -push-default-apps true"
  args:
    chdir: "{{ splunk_installation.splunk_home_path}}/bin"
  with_items: "{{ groups['shcmember'][0] }}"
  when: deployer_cleanup_complete|succeeded
